# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "Docs"
repo_url: https://github.com/readysettech/docs
repo_name: readysettech/docs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    # - navigation.sections
    - navigation.expand
    - navigation.indexes
    # - navigation.path
    - navigation.top
    - header.autohide
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.action.edit
    - content.action.view
  font:
    # Fonts for everything but headings
    # Heading fonts defined in stylesheets/extra.css
    text: Inter
    code: Roboto Mono
  favicon: assets/favicon.png
  custom_dir: docs/overrides
  icon:
    logo: main/logo
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      tip: fontawesome/solid/bullhorn
      warning: fontawesome/solid/triangle-exclamation

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Guides:
    - Intro:
      - What is ReadySet?: guides/intro/intro.md
      - Quickstart: guides/intro/quickstart.md
      - Playground: guides/intro/playground.md
    - Deploy:
      - Production Notes: guides/deploy/production-notes.md
      - Deploy with ReadySet Cloud: guides/deploy/deploy-readyset-cloud.md
      - Deploy with Kubernetes: guides/deploy/deploy-readyset-kubernetes.md
      - Deploy with Binary: guides/deploy/deploy-readyset-binary.md
    - Connect:
      - guides/connect/index.md
      - Node.js: guides/connect/nodejs.md
      - Python: guides/connect/python.md
      - Ruby: guides/connect/ruby.md
      - Go: guides/connect/go.md
    - Cache:
      - Profile Queries: guides/cache/profile-queries.md
      - Check Snapshotting: guides/cache/check-snapshotting.md
      - Cache Queries: guides/cache/cache-queries.md
    # - Manage ReadySet:
    #   - Upgrade ReadySet: guides/upgrade-readyset.md
    #   - Scale ReadySet: guides/scale-readyset.md
  - Reference:
    - SQL: reference/sql-support.md
    - CLI:
      - reference/cli/index.md
      - readyset: reference/cli/readyset.md
      - readyset-server: reference/cli/readyset-server.md
    - Telemetry: reference/telemetry.md
  - Concepts:
    - Overview: concepts/overview.md
    - Dataflow: concepts/dataflow.md
    - Example Use Case: concepts/example.md
    - Memory Efficiency: concepts/efficiency.md
  - Releases:
    - ReadySet Core: releases/readyset-core.md

extra_css:
  - stylesheets/extra.css

copyright: Â© 2023 ReadySet Technology Inc.

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/readyset
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/readysetio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/readysettech/
  analytics:
    provider: google
    property: G-QHKR2RLDNK
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Helpful
          data: helpful
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Not helpful
          data: not-helpful
          note: >-
            Thanks for your feedback!<br><a href="https://github.com/readysettech/docs/issues/new?title=[Feedback]+{title}+-+{url}&amp;body=%23%23%20What is the reason for your feedback?%0A%0A&#91;%20&#93;%20Missing the information I need%0A%0A&#91;%20&#93;%20Too complicated%0A%0A&#91;%20&#93;%20Out of date%0A%0A&#91;%20&#93;%20Something is broken%0A%0A&#91;%20&#93;%20Other%0A%0A%23%23%20Additional details&amp;" target="blank" rel="noopener">Please tell us more.</a>

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true
      toc_depth: 3
